Return a string, not a Path.
Bottle doesn't know how to deal with a Path.

Traceback (most recent call last):
  File "/usr/home/freebsd/prototype-karma/bottle.py", line 1005, in _handle
    out = route.call(**args)
  File "/usr/home/freebsd/prototype-karma/bottle.py", line 2017, in wrapper
    rv = callback(*a, **ka)
  File "/usr/home/freebsd/prototype-karma/server.py", line 176, in newkey
    return static_file(filename, root=abspath('clavinger'), download=filename)
  File "/usr/home/freebsd/prototype-karma/bottle.py", line 2883, in static_file
    filename = os.path.abspath(os.path.join(root, filename.strip('/\\')))
AttributeError: 'PosixPath' object has no attribute 'strip'